# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 674)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(350, 240))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../posture-images/encorvado.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.webcam = QtWidgets.QLabel(self.centralwidget)
        self.webcam.setEnabled(True)
        self.webcam.setMaximumSize(QtCore.QSize(640, 480))
        self.webcam.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.webcam.setText("")
        self.webcam.setScaledContents(True)
        self.webcam.setObjectName("webcam")
        self.gridLayout.addWidget(self.webcam, 3, 0, 1, 1)
        self.send_data = QtWidgets.QPushButton(self.centralwidget)
        self.send_data.setObjectName("send_data")
        self.gridLayout.addWidget(self.send_data, 4, 0, 1, 1)
        self.instructions = QtWidgets.QLabel(self.centralwidget)
        self.instructions.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.instructions.setFont(font)
        self.instructions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.instructions.setScaledContents(True)
        self.instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.instructions.setObjectName("instructions")
        self.gridLayout.addWidget(self.instructions, 2, 1, 1, 1)
        self.contador = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.contador.setFont(font)
        self.contador.setAlignment(QtCore.Qt.AlignCenter)
        self.contador.setObjectName("contador")
        self.gridLayout.addWidget(self.contador, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1206, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_data.setText(_translate("MainWindow", "Send data"))
        self.instructions.setText(_translate("MainWindow", "Por favor sientate como se muestra en la imagen"))
        self.contador.setText(_translate("MainWindow", "5"))
